---
default:
    image: golang:1-trixie
    interruptible: true

stages:
    - lint
    - test
    - build
    - publish

.go-cache:
    variables:
        GOPATH: $CI_PROJECT_DIR/.go
    before_script:
        - mkdir -p .go
    cache:
        key:
            files:
                - go.sum
        paths:
            - .go/pkg/mod/

lint:
    stage: lint
    image: golangci/golangci-lint:latest
    script:
        - golangci-lint fmt -d
        - golangci-lint run

test:
    stage: test
    extends: .go-cache
    script:
        - make test
        - go run github.com/bobg/mingo/cmd/mingo@latest -v -check -tests

build:
    stage: build
    extends: .go-cache
    script:
        - make VERSION="${CI_COMMIT_TAG:-$CI_PIPELINE_ID}" build-release
    artifacts:
        paths:
            - $CI_PROJECT_NAME
        expire_in: 1 day

publish:
    stage: publish
    image: registry.gitlab.com/gitlab-org/cli:latest
    interruptible: false
    rules:
        - if: $CI_COMMIT_TAG
    before_script:
        - glab auth login -j $CI_JOB_TOKEN
    script:
        - glab changelog generate -v $CI_COMMIT_TAG > ./description.md
    after_script:
        - glab release upload --use-package-registry --package-name $CI_PROJECT_NAME $CI_COMMIT_TAG ./$CI_PROJECT_NAME
    release:
        tag_name: $CI_COMMIT_TAG
        description: ./description.md
